# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deneme.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QPushButton, QLabel, QHBoxLayout

class MainWindow(QWidget):
    def __init__(self):
        super().__init__()

        self.setWindowTitle("Data Collection Software")
        self.setGeometry(100, 100, 400, 300)

        self.initUI()

    def initUI(self):
    
        layout = QVBoxLayout()

        label = QLabel("Welcome to our Software Project", self)
        layout.addWidget(label)

        button_layout = QVBoxLayout()

        btn_car_valuation = QPushButton("Second-hand Car Valuation", self)
        btn_car_valuation.clicked.connect(self.car_valuation)
        button_layout.addWidget(btn_car_valuation)

        btn_football_prediction = QPushButton("Football Match Result Prediction", self)
        btn_football_prediction.clicked.connect(self.football_prediction)
        button_layout.addWidget(btn_football_prediction)

        btn_voice_command = QPushButton("Voice Command Database Creation", self)
        btn_voice_command.clicked.connect(self.voice_command)
        button_layout.addWidget(btn_voice_command)

        layout.addLayout(button_layout)

        self.setLayout(layout)

    def car_valuation(self):
        print("Second-hand Car Valuation project started!")

    def football_prediction(self):
        print("Football Match Result Prediction project started!")

    def voice_command(self):
        print("Voice Command Database Creation project started!")


if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
