# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voiceshow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(917, 466)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_toplam_kayit = QtWidgets.QLabel(self.centralwidget)
        self.label_toplam_kayit.setGeometry(QtCore.QRect(100, 50, 101, 16))
        self.label_toplam_kayit.setObjectName("label_toplam_kayit")
        self.label_kiz_kayit = QtWidgets.QLabel(self.centralwidget)
        self.label_kiz_kayit.setGeometry(QtCore.QRect(120, 90, 81, 16))
        self.label_kiz_kayit.setObjectName("label_kiz_kayit")
        self.label_erkek_kayit = QtWidgets.QLabel(self.centralwidget)
        self.label_erkek_kayit.setGeometry(QtCore.QRect(140, 130, 111, 16))
        self.label_erkek_kayit.setObjectName("label_erkek_kayit")
        self.pushButton_kelime_ekle = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_kelime_ekle.setGeometry(QtCore.QRect(240, 12, 71, 21))
        self.pushButton_kelime_ekle.setObjectName("pushButton_kelime_ekle")
        self.pushButton_kelime_sil = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_kelime_sil.setGeometry(QtCore.QRect(610, 12, 71, 21))
        self.pushButton_kelime_sil.setObjectName("pushButton_kelime_sil")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 12, 65, 16))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 114, 16))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 79, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 12, 137, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(460, 12, 137, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(10, 170, 891, 241))
        self.treeWidget.setLineWidth(1)
        self.treeWidget.setColumnCount(10)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.treeWidget.header().setDefaultSectionSize(110)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(133, 41, 137, 16))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(12, 12, 70, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 99, 16))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 917, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_toplam_kayit.setText(_translate("MainWindow", "TextLabel"))
        self.label_kiz_kayit.setText(_translate("MainWindow", "TextLabel"))
        self.label_erkek_kayit.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_kelime_ekle.setText(_translate("MainWindow", "Ekle"))
        self.pushButton_kelime_sil.setText(_translate("MainWindow", "Sil"))
        self.label.setText(_translate("MainWindow", "Kelime Sil :"))
        self.label_5.setText(_translate("MainWindow", "Erkek Toplam Kayıt:"))
        self.label_3.setText(_translate("MainWindow", "Toplam Kayıt:"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Işığı"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Alarmı"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "Multimedyayı"))
        self.treeWidget.headerItem().setText(3, _translate("MainWindow", "Aydınlatmayı"))
        self.treeWidget.headerItem().setText(4, _translate("MainWindow", "Parlaklığı"))
        self.treeWidget.headerItem().setText(5, _translate("MainWindow", "İklimlendirmeyi"))
        self.treeWidget.headerItem().setText(6, _translate("MainWindow", "Odayı"))
        self.treeWidget.headerItem().setText(7, _translate("MainWindow", "Fanı"))
        self.treeWidget.headerItem().setText(8, _translate("MainWindow", "Isıtmayı"))
        self.treeWidget.headerItem().setText(9, _translate("MainWindow", "Sıcaklığı"))
        self.label_2.setText(_translate("MainWindow", "Kelime Ekle:"))
        self.label_4.setText(_translate("MainWindow", "Kız Toplam Kayıt:"))

class VoiceShow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(VoiceShow, self).__init__()
        self.setupUi(self)
        self.initialize_ui()

    def initialize_ui(self):
      
        self.pushButton_kelime_ekle.clicked.connect(self.add_word)
        self.pushButton_kelime_sil.clicked.connect(self.delete_word)

    def add_word(self):
      
        kelime = self.lineEdit.text()
        if kelime:
           
            item = QtWidgets.QTreeWidgetItem([kelime])
            self.treeWidget.addTopLevelItem(item)
            self.lineEdit.clear()
        else:
            QtWidgets.QMessageBox.warning(self, "Uyarı", "Kelime alanı boş olamaz!")

    def delete_word(self):
     
        selected_items = self.treeWidget.selectedItems()
        if selected_items:
            for item in selected_items:
                index = self.treeWidget.indexOfTopLevelItem(item)
                self.treeWidget.takeTopLevelItem(index)
        else:
            QtWidgets.QMessageBox.warning(self, "Uyarı", "Lütfen silmek için bir kelime seçin!")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    voiceshow = VoiceShow()
    voiceshow.show()
    sys.exit(app.exec_())

